FROM node:20-slim


RUN apt-get update && apt-get install -y wget curl git build-essential libssl-dev pkg-config && rm -rf /var/lib/apt/lists/*


RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
ENV PATH="/root/.cargo/bin:${PATH}"


RUN cargo install leo-lang


RUN cp /root/.cargo/bin/leo /usr/local/bin/leo || true


WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci
RUN npm install -g tsx

COPY src/ ./src/

COPY docker-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

EXPOSE 8545 6000

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
